// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notifications.Infrastructure.Persistence;

#nullable disable

namespace Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260903173117_AddNotificationPreferences")]
    partial class AddNotificationPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Notifications.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Metadata")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TypeValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Notifications.Domain.Entities.PreferenciasDeNotificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ExportacionLista")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MentionEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProjectUpdated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("QuietHoursEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeOnly>("QuietHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("QuietHoursStart")
                        .HasColumnType("time");

                    b.Property<bool>("TaskAssigned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TaskCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TaskDueSoon")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("TicketCreated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TicketUpdated")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationPreferences_Tenant_User");

                    b.ToTable("NotificationPreferences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
