<Project>
  <ItemGroup>
    <PackageReference Update="MediatR" Version="12.5.0" />
    <PackageReference Update="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Relational" Version="9.0.5" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Design" Version="9.0.5" />
    <PackageReference Update="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>
</Project>
