// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teams.Infrastructure.Persistence;

#nullable disable

namespace Teams.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TeamsDbContext))]
    [Migration("20260701200158_InitialTeams")]
    partial class InitialTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Teams.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Teams.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("Teams.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Teams.Domain.Entities.Team", null)
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Teams.Domain.ValueObjects.TeamRole", "Role", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("char(36)");

                            b1.Property<bool>("CanManageMembers")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("CanManageMembers");

                            b1.Property<bool>("CanManageProjects")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("CanManageProjects");

                            b1.Property<bool>("CanManageTasks")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("CanManageTasks");

                            b1.Property<bool>("CanManageTickets")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("CanManageTickets");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("RoleName");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("Teams.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
