// <auto-generated />
using System;
using Automations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Automations.Infrastructure.Migrations
{
    [DbContext(typeof(AutomationsDbContext))]
    [Migration("20260929212840_RenameAutomationsToEnglish")]
    partial class RenameAutomationsToEnglish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Automations.Domain.Entities.AutomationExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RuleId", "AtUtc")
                        .HasDatabaseName("IX_AutomationExecutions_History");

                    b.HasIndex("TenantId", "RuleId", "EntityId", "Day")
                        .HasDatabaseName("IX_AutomationExecutions_DailyMemory");

                    b.ToTable("AutomationExecutions", (string)null);
                });

            modelBuilder.Entity("Automations.Domain.Entities.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastExecutedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_AutomationRules_Tenant_Name");

                    b.HasIndex("TenantId", "Trigger", "IsActive")
                        .HasDatabaseName("IX_AutomationRules_Tenant_Trigger_IsActive");

                    b.ToTable("AutomationRules", (string)null);
                });

            modelBuilder.Entity("Automations.Domain.Entities.AutomationRule", b =>
                {
                    b.OwnsMany("Automations.Domain.Entities.AutomationAction", "Actions", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)");

                            b1.HasKey("AutomationRuleId", "Id");

                            b1.ToTable("AutomationActions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId");
                        });

                    b.OwnsMany("Automations.Domain.Entities.AutomationCondition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<string>("Field")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Operator")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)");

                            b1.HasKey("AutomationRuleId", "Id");

                            b1.ToTable("AutomationConditions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId");
                        });

                    b.Navigation("Actions");

                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
