// <auto-generated />
using System;
using Automations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Automations.Infrastructure.Migrations
{
    [DbContext(typeof(AutomationsDbContext))]
    partial class AutomationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Automations.Domain.Entities.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Disparador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UltimaEjecucionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VecesEjecutada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_AutomationRules_Tenant_Nombre");

                    b.HasIndex("TenantId", "Disparador", "Activa")
                        .HasDatabaseName("IX_AutomationRules_Tenant_Disparador_Activa");

                    b.ToTable("AutomationRules", (string)null);
                });

            modelBuilder.Entity("Automations.Domain.Entities.AutomationRule", b =>
                {
                    b.OwnsMany("Automations.Domain.Entities.AccionDeAutomatizacion", "Acciones", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)");

                            b1.HasKey("AutomationRuleId", "Id");

                            b1.ToTable("AutomationActions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId");
                        });

                    b.OwnsMany("Automations.Domain.Entities.CondicionDeAutomatizacion", "Condiciones", b1 =>
                        {
                            b1.Property<Guid>("AutomationRuleId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<string>("Campo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Operador")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Valor")
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)");

                            b1.HasKey("AutomationRuleId", "Id");

                            b1.ToTable("AutomationConditions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AutomationRuleId");
                        });

                    b.Navigation("Acciones");

                    b.Navigation("Condiciones");
                });
#pragma warning restore 612, 618
        }
    }
}
