// <auto-generated />
using System;
using CustomFields.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomFields.Infrastructure.Migrations
{
    [DbContext(typeof(CustomFieldsDbContext))]
    [Migration("20260929202621_RenameCustomFieldsToEnglish")]
    partial class RenameCustomFieldsToEnglish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CustomFields.Domain.Entities.CustomFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Formula")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TargetEntity", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomFieldDefinitions_Tenant_TargetEntity_Name");

                    b.ToTable("CustomFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("CustomFields.Domain.Entities.CustomFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntityId")
                        .HasDatabaseName("IX_CustomFieldValues_Tenant_Entity");

                    b.HasIndex("TenantId", "DefinitionId", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomFieldValues_Tenant_Definition_Entity");

                    b.ToTable("CustomFieldValues", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
