// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkItems.Infrastructure.Persistence;

#nullable disable

namespace WorkItems.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkItemsDbContext))]
    [Migration("20260813005354_AddTaskAssignees")]
    partial class AddTaskAssignees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WorkItems.Domain.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DependsOnTaskId")
                        .HasDatabaseName("IX_TaskDependencies_Tenant_DependsOn");

                    b.HasIndex("TenantId", "TaskId", "DependsOnTaskId")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskDependencies_Tenant_Task_DependsOn");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("WorkItems.Domain.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("EstimatedHours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.PrimitiveCollection<string>("TagIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.ComplexProperty<Dictionary<string, object>>("Priority", "WorkItems.Domain.Entities.WorkTask.Priority#TaskPriority", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasDefaultValue("Normal");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasDefaultValue("Normal");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Status", "WorkItems.Domain.Entities.WorkTask.Status#TaskStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "WorkItems.Domain.Entities.WorkTask.Title#TaskTitle", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ParentTaskId")
                        .HasDatabaseName("IX_Tasks_TenantId_ParentTaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WorkItems.Domain.Entities.WorkTask", b =>
                {
                    b.OwnsMany("WorkItems.Domain.Entities.TaskAssignee", "Assignees", b1 =>
                        {
                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)")
                                .HasColumnName("UserId");

                            b1.HasKey("WorkTaskId", "UserId");

                            b1.ToTable("TaskAssignees", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.Navigation("Assignees");
                });
#pragma warning restore 612, 618
        }
    }
}
