// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkItems.Infrastructure.Persistence;

#nullable disable

namespace WorkItems.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkItemsDbContext))]
    [Migration("20260917205554_RenameWorkItemsToEnglish")]
    partial class RenameWorkItemsToEnglish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WorkItems.Domain.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DependsOnTaskId")
                        .HasDatabaseName("IX_TaskDependencies_Tenant_DependsOn");

                    b.HasIndex("TenantId", "TaskId", "DependsOnTaskId")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskDependencies_Tenant_Task_DependsOn");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("WorkItems.Domain.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("EstimatedHours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.PrimitiveCollection<string>("TagIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.ComplexProperty<Dictionary<string, object>>("Priority", "WorkItems.Domain.Entities.WorkTask.Priority#TaskPriority", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasDefaultValue("Normal");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasDefaultValue("Normal");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Status", "WorkItems.Domain.Entities.WorkTask.Status#TaskStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "WorkItems.Domain.Entities.WorkTask.Title#TaskTitle", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompletedAtUtc")
                        .HasDatabaseName("IX_Tasks_TenantId_CompletedAtUtc");

                    b.HasIndex("TenantId", "ParentTaskId")
                        .HasDatabaseName("IX_Tasks_TenantId_ParentTaskId");

                    b.HasIndex("TenantId", "ArchivedAtUtc", "IsDeleted")
                        .HasDatabaseName("IX_Tasks_TenantId_ArchivedAtUtc_IsDeleted");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WorkItems.Domain.Entities.WorkTask", b =>
                {
                    b.OwnsMany("WorkItems.Domain.Entities.ChecklistItem", "Checklist", b1 =>
                        {
                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<bool>("IsDone")
                                .HasColumnType("tinyint(1)");

                            b1.Property<int>("Position")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.HasKey("WorkTaskId", "Id");

                            b1.ToTable("TaskChecklistItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsMany("WorkItems.Domain.Entities.TaskAssignee", "Assignees", b1 =>
                        {
                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)")
                                .HasColumnName("UserId");

                            b1.HasKey("WorkTaskId", "UserId");

                            b1.ToTable("TaskAssignees", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.OwnsOne("WorkItems.Domain.ValueObjects.RecurrencePattern", "Recurrence", b1 =>
                        {
                            b1.Property<Guid>("WorkTaskId")
                                .HasColumnType("char(36)");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("Recurrence_EndDate");

                            b1.Property<string>("Frequency")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Recurrence_Frequency");

                            b1.Property<int>("Interval")
                                .HasColumnType("int")
                                .HasColumnName("Recurrence_Interval");

                            b1.Property<DateOnly>("NextOccurrence")
                                .HasColumnType("date")
                                .HasColumnName("Recurrence_NextOccurrence");

                            b1.Property<int>("SeriesDay")
                                .HasColumnType("int")
                                .HasColumnName("Recurrence_SeriesDay");

                            b1.HasKey("WorkTaskId");

                            b1.HasIndex("NextOccurrence")
                                .HasDatabaseName("IX_Tasks_Recurrence_NextOccurrence");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("WorkTaskId");
                        });

                    b.Navigation("Assignees");

                    b.Navigation("Checklist");

                    b.Navigation("Recurrence");
                });
#pragma warning restore 612, 618
        }
    }
}
