// <auto-generated />
using System;
using Comments.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comments.Infrastructure.Migrations
{
    [DbContext(typeof(CommentsDbContext))]
    [Migration("20261008162225_CommentMentions")]
    partial class CommentMentions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Comments.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EditedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Comments_TenantId_EntityType_EntityId_CreatedAtUtc");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Comments.Domain.Entities.Comment", b =>
                {
                    b.OwnsMany("Comments.Domain.Mentions.CommentMention", "Mentions", b1 =>
                        {
                            b1.Property<Guid>("CommentId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Type")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)");

                            b1.HasKey("CommentId", "Type", "EntityId");

                            b1.HasIndex("Type", "EntityId")
                                .HasDatabaseName("IX_CommentMentions_Type_EntityId");

                            b1.ToTable("CommentMentions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CommentId");
                        });

                    b.Navigation("Mentions");
                });
#pragma warning restore 612, 618
        }
    }
}
