// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporting.Infrastructure.Persistence;

#nullable disable

namespace Reporting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260907144812_ConstructorYProgramacionDeInformes")]
    partial class ConstructorYProgramacionDeInformes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Reporting.Domain.Entities.ContenidoDeExportacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("LONGBLOB");

                    b.Property<Guid>("ExportacionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipoDeContenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExportacionId")
                        .IsUnique()
                        .HasDatabaseName("UX_ContenidosDeExportacion_ExportacionId");

                    b.ToTable("ContenidosDeExportacion");
                });

            modelBuilder.Entity("Reporting.Domain.Entities.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.PrimitiveCollection<string>("TagIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WidgetsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("Reporting.Domain.Entities.Exportacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ComenzadaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.Property<int>("EstadoValue")
                        .HasColumnType("int");

                    b.Property<int>("FormatoValue")
                        .HasColumnType("int");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<string>("NombreDeFichero")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SolicitadaPorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SolicitadaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("TerminadaUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoValue", "SolicitadaUtc")
                        .HasDatabaseName("IX_Exportaciones_Estado_Solicitada");

                    b.HasIndex("TenantId", "ReportId")
                        .HasDatabaseName("IX_Exportaciones_TenantId_ReportId");

                    b.ToTable("Exportaciones");
                });

            modelBuilder.Entity("Reporting.Domain.Entities.ProgramacionDeInforme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreadaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("FormatoValue")
                        .HasColumnType("int");

                    b.Property<int>("FrecuenciaValue")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("UltimoDiaGenerado")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Activa")
                        .HasDatabaseName("IX_Programaciones_Activa");

                    b.HasIndex("TenantId", "ReportId")
                        .HasDatabaseName("IX_Programaciones_TenantId_ReportId");

                    b.ToTable("Programaciones");
                });

            modelBuilder.Entity("Reporting.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("DefinicionJson")
                        .HasColumnType("longtext");

                    b.Property<int>("FormatValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Parameters")
                        .HasColumnType("longtext");

                    b.PrimitiveCollection<string>("TagIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TypeValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
